---
- name: install sos via dnf
  dnf: name={{ item }} state=latest
  with_items:
    - sos
  when: ansible_pkg_mgr == 'dnf'

- name: install sos via yum
  yum: name={{ item }} state=latest
  with_items:
    - sos
  when: ansible_pkg_mgr == 'yum'

- name: install sos via apt
  apt: name={{ item }} state=latest
  with_items:
    - sosreport
  when: ansible_pkg_mgr == 'apt'
